### ISSUE TITLE
Problem with selectROI

### ISSUE THREAD

**Issue by onurtore** [ros-gbp/opencv3-release#3]
Hello, 
There is a problem with selectROI function with opencv3 package, i cant select when press enter or space, i think the original problem fixed with opencv_contrib package but ros package still have the same problem, is there any idea how to fix this ?

**Comment by vrabaud** [comment]
I am not familiar with that function, do you have the commit for which is was fixed in opencv_contrib ? Thx

**Comment by vrabaud** [comment]
https://github.com/opencv/opencv_contrib/commit/19b72cc41ef69825cfdf631012b94ef4a6087cb8#diff-a883bfa3e08b8c403c82df0b063b9a8e ?

**Comment by onurtore** [comment]
yes i think thats it, neccessary changes for working properly with other OS, without it, i can't end selectROI function

**Comment by vrabaud** [comment]
This is fine in Kinetic as we have a version fomr May 25th.
Which distro are you on ? Which platform ?

**Comment by onurtore** [comment]
i tried it with ubuntu 16.04 Kinetic but that' s not solved my problem, is this problem just for me    can you please try the function in your own pc ,  sample code is in [there.](http://docs.opencv.org/3.1.0/d2/d0a/tutorial_introduction_to_tracker.html#gsc.tab=0).

**Comment by vrabaud** [comment]
hmmm, and do you have it working with a custom OpenCV that you built yourself ? If so, which version ? Thx.

**Comment by onurtore** [comment]
So right now its looks like i solved the problem, with ubuntu 14.04 and indigo the algorithms works ( the problem  probably about  kinetic  so i am not sure about the reason )

I have another problems right now like using opencv package with cv_bridge  i get seg fault error but this is anoher problem.

**Comment by vrabaud** [comment]
the release does not have the fix, you are right: https://github.com/ros-gbp/opencv3-release/blob/release/kinetic/opencv3/opencv_contrib/tracking/src/roiSelector.cpp#L113

**Comment by vrabaud** [comment]
fixed in https://github.com/ros/rosdistro/pull/12225
